### ISSUE TITLE
Add Semantic-UI popups to navbar items

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#109]
Right now we have single word navbar menu items.  This is nice from a design perspective, but not so nice from a usability perspective.

So I propose adding [controlled semantic-ui popups](https://react.semantic-ui.com/modules/popup#popup-example-controlled) to these items, popping up after something like ~1 second, hopefully fading in.  

There's some helpful example code there.

**Comment by tanmayanand44** [comment]
@JohnAllen Ok John,lets discuss here first.I think popups should be after a 1/2 seconds lag almost every website have these kind of popups after a lag.What are your views?
