### ISSUE TITLE
Move PullRequestListItem to components and out of pages

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#111]

**Comment by tanmayanand44** [comment]
@JohnAllen I wish to work on this issue.Can you give me a little bit guidance.

**Comment by JohnAllen** [comment]
Yeah this one is super simple. Just move the FILE `PullRequestListItem.jsx` out of the pages directory into the components directory.

Pretty sure that was it :)

Thanks!

**Comment by tanmayanand44** [comment]
@JohnAllen Yeah sure
