### ISSUE TITLE
Make mobile navbar menu hamburger menu + responsive

### ISSUE THREAD

**Issue by tanmayanand44** [Distense/distense-ui#129]
The current website doesn't seem to work perfectly in mobiles/tablet screens.The site needs a responsive mobile design.

**Comment by JohnAllen** [comment]
Totally agree.

How much experience do you have with this?

Wonder how much built-in stuff Semantic-UI has with this stuff.

**Comment by tanmayanand44** [comment]
I once implemented a responsive web design.In that normally when browser length was big than some pixels then all the elements were shown in form of tabs like in present Distense website.And when viewed on mobile it shows that elements in forms of a side menu bar on clicking the bars.
PS:I used html and css.

**Comment by JohnAllen** [comment]
yeah that's the first thing that should happen.  We use [`react.semantic-ui.com`](react.semantic-ui.com) which may have something built in.

**Comment by tanmayanand44** [comment]
Ok I will work on it.But it will take a plenty of time,so I can try to finish it in a week.

**Comment by JohnAllen** [comment]
Sounds good -- thanks!  Let me know if you get stuck.

**Comment by JohnAllen** [comment]
Semantic-UI does have some responsive stuff: https://react.semantic-ui.com/addons/responsive#responsive-example-content

Once you start, or probably before, let's talk more about exactly should be done.  First thing is the hamburger menu.

But let's talk about how you're going to build it and how it will be organized, so we kind of start on solid footing, because making the whole site responsive is important and would be great to start with the way the whole site will be responsive.

**Comment by tanmayanand44** [comment]
Yeah sure.

**Comment by JohnAllen** [comment]
@tanmayanand44 let me know if I can help with this...

**Comment by tanmayanand44** [comment]
@JohnAllen I am a bit busy these days since my exams are approaching,so I am unable to work now on this issue.
But I will surely do it once my exams get over.

**Comment by JohnAllen** [comment]
@tanmayanand44 Hope your exams go well!

**Comment by tanmayanand44** [comment]
@JohnAllen Thanks!

**Comment by tanmayanand44** [comment]
@JohnAllen I have started working on this.

**Comment by tanmayanand44** [comment]
@JohnAllen How's this?
![screenshot from 2018-03-03 16-53-55](https://user-images.githubusercontent.com/33908900/36933699-c1f6473a-1f03-11e8-8323-fd4145e65962.png)

**Comment by JohnAllen** [comment]
@tanmayanand44 this is for a mobile view

**Comment by tanmayanand44** [comment]
@JohnAllen As a first step, I have made the menu for both now.I am facing some issue in porting the Response class from react-semantic-ui.All the time it shows error.You may guide.

**Comment by JohnAllen** [comment]
@tanmayanand44 I can't really guide for this.  Need to see this in a mobile window, also the buttons need to be bigger for thumbs

**Comment by tanmayanand44** [comment]
@JohnAllen The menu was fine when I saw it in mobile.Problem is that if we can remove those horizontal menu tabs in mobile view,then it's done.

**Comment by tanmayanand44** [comment]
@JohnAllen Do we have any kind of filter function in semantic-ui?

**Comment by JohnAllen** [comment]
Not sure what that is
