### ISSUE TITLE
Add image of name/logo from website to README

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#131]
Just tried to do this using imgur but the link said non-image content type detected for some reason.

**Comment by JohnAllen** [comment]
It's slightly technical.  Can make this commit in the browser.

**Comment by Atul9** [comment]
Hi @JohnAllen, does #132 fixes this issue?

**Comment by JohnAllen** [comment]
Yes, it does but we need the same thing done in our `distense-contracts` repo if you want to help there.  Should be easy to do with the same image.

Good catch with 132

**Comment by JohnAllen** [comment]
@Atul9  https://github.com/Distense/distense-contracts/issues/8 Thanks!
