### ISSUE TITLE
Add "What are DID?" to the FAQ [30 DID reward]

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#137]
- DID are our economic and governance token
- They represent ownership of Distense
- They give the owner the right to: 
    - Propose/add tasks to Distense
    - Vote on Distense parameters (add link to https://disten.se/parameters)
    - Approve work
    - Receive dividends if Distense earns money

**Comment by JohnAllen** [comment]
30 DID

**Comment by Atul9** [comment]
@JohnAllen what is full form of DID?

**Comment by JohnAllen** [comment]
That's it.  Distense DID.  You did something so you get DID : )
