### ISSUE TITLE
Commit build files to repo

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#154]
*** Commit build files to repo *** 

This will speed up deployment

- `npm install`
- `npm run build`
- `git add build`
- `git commit -m "Add build files to repo"`

**Comment by Yogendra0Sharma** [comment]
@JohnAllen I have submitted one pull request for this issue, please review it.
https://github.com/Yogendra0Sharma/distense-ui/commit/7b13e101103c3bff465b944b86371b52faf8aa26

**Comment by JohnAllen** [comment]
Want to submit the pull request in this repo?  Then we can run our checks.
