### ISSUE TITLE
Create FAQ page with FAQs

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#95]

**Comment by tanmayanand44** [comment]
@JohnAllen I wish to create this page.Can you tell what kind of FAQ's should I add(like about tasks reward/contributing guidelines or something else).

**Comment by JohnAllen** [comment]
Awesome @tanmayanand44 ! Yeah, let's do that here.

Tips
- I suggest cloning the `HowItWorks` page in `pages`
  - It has some of the intra-page hyperlinking code we need for this

**FAQs**

_(Feel free to reword these)_
1. Q: Is Distense like other companies that are for connecting labor to companies who need development jobs done -- possibly like outsourcing companies?
  - A: No, Distense is a single organization whose labor is for internal purposes and building blockchain applications  that will generate revenue from third parties.

**Comment by tanmayanand44** [comment]
@JohnAllen Yeah sure.Should I also add about how to contribute and view tasks,rewards etc.

**Comment by JohnAllen** [comment]
Sure, though some of that is already on HowItWorks.  How did you find Distense @tanmayanand44 ?

**Comment by tanmayanand44** [comment]
@JohnAllen My friend told me about it.I am a fairly experienced in frontend and wish to conribute to distense.
