### ISSUE TITLE
Add up and down voting buttons in Parameters page to simplify voting

### ISSUE THREAD

**Issue by JohnAllen** [Distense/distense-ui#97]
Basically instead of scalar number text inputs, we should probably have buttons that vote up or down by the maximum allowed.  

Most people will want to increase the value by the maximum possible and this will simplify the process.

- Uncomment the `<Button.Group>` already in the page on [line 49](https://github.com/Distense/distense-ui/blob/master/src/pages/Parameters.js#L149)
- Auto fill the value in both the button state (probably somewhere in the parameter <Card>) and `onSubmit` function

**Comment by 7ayushgupta** [comment]
Is this issue open to being worked upon?

**Comment by JohnAllen** [comment]
Actually I completed this one as well.  Will close and review others to make sure there are aren't others that should be closed.

**Comment by 7ayushgupta** [comment]
Okay!
